services:
  moedelolk:
    build: .
    container_name: moedelolk
    restart: always
    ports:
      - "8081:8000"
    environment:
      - DJANGO_DEBUG=false
      - DJANGO_ALLOWED_HOSTS=*
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./staticfiles:/app/staticfiles
      - ./uploads:/app/uploads
